name: Bug report
description: Something isn't working as documented
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: "2.0.0"
    validations:
      required: true
  - type: input
    id: subscriptions
    attributes:
      label: crumbls/subscriptions version
      placeholder: "2.0.0"
    validations:
      required: true
  - type: input
    id: php
    attributes:
      label: PHP version
      placeholder: "8.3.10"
    validations:
      required: true
  - type: input
    id: laravel
    attributes:
      label: Laravel version
      placeholder: "12.0"
    validations:
      required: true
  - type: input
    id: filament
    attributes:
      label: Filament version
      placeholder: "5.0"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
